version: '3'
services: 

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    tty: true
    entrypoint: dockerize -wait http://node:3000 -timeout 30s
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - desafio-network
    ports: 
      - "8080:8080"
    depends_on:
      - node
  
  node:
    build:
      context: node
      dockerfile: Dockerfile.node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: ["node", "server.js"]
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - desafio-network
    ports:
      - "3000:3000"
    depends_on: 
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - desafio-network
      
networks: 
  desafio-network: 
    driver: bridge
